### ISSUE TITLE
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated.

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-php#11]
When running the `debops.php` role, I get the warning from Ansible:

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:

http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse

 for currently supported syntax regarding 
included files and variables.
This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

By quick checking, I traced the issue to [this code](https://github.com/debops/ansible-php/blob/master/tasks/main.yml#L20-L25) which was merged in https://github.com/debops/ansible-php/commit/845772ef667119b7e98ca8b3fbf7355c0021707f. @ypid, any idea how to fix or rewrite it to stop Ansible from emitting a warning?

**Comment by ypid** [comment]
Only on Ansible 2.0.

**Comment by drybjed** [comment]
Sounds good then, it shouldn't be a problem on later Ansible releases.
