### ISSUE TITLE
php__version is undefined

### ISSUE THREAD

**Issue by izolate** [debops/ansible-php#12]
Thanks for building this role, but there appears to be a bug causing the variable `php__version` to be undefined.

```
{
  "failed": true,
  "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'php__version' is undefined\n\nThe error appears to have been in '/path/to/roles/debops.php/tasks/main.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install PHP packages\n  ^ here\n"
}
```

Ansible 2.x running the default role settings.

**Comment by drybjed** [comment]
Do you use this role with a custom playbook? You need to include all the roles specified in the example playbook for the role to work correctly, especially `debops.php/env` role where `php__version` is defined.

**Comment by izolate** [comment]
@drybjed Cheers for that. Solved by adding the following to my `playbook.yml`:

```
roles:
  - role: debops.php/env
    tags: ['role::php', 'role::apt_preferences', 'role::logrotate']
```
