### ISSUE TITLE
Installing php packages assumes all package names are prefixed with php-<php__version>

### ISSUE THREAD

**Issue by pulse00** [debops/ansible-php#14]
It seems php module packages don't have a generic prefix with the php version, e.g. `php7.0-apcu` or `php5.0-apcu`. apcu for example is named `php-apcu`.

I stumbled upon this during an owncloud installation, where i tried to fix it in [debops.owncloud](https://github.com/debops/ansible-owncloud/pull/60) but apparently this breaks php 5. 

Don't know how to solve this in this role as i'm not familiar enough with either php module packaging nor debops php handling.

**Comment by drybjed** [comment]
Try adding the 'php-apcu' package to list of APT packages passed to the
debops.php role. It should detect the php- prefix and install the package
correctly.
18 wrz 2016 23:02 "Robert Gründler" notifications@github.com napisał(a):

**Comment by pulse00** [comment]
> Try adding the 'php-apcu' package to list of APT packages passed to the debops.php role. It should detect the php- prefix and install the package correctly.

yeah, that's what i did in the pull request here https://github.com/debops/ansible-owncloud/pull/60 but as far is i understand this is not a generic approach and breaks php5 support.

**Comment by drybjed** [comment]
I'm currently AFK. Is the PHP5 version of the package named differently?
18 wrz 2016 23:08 "Robert Gründler" notifications@github.com napisał(a):

**Comment by ypid** [comment]
@drybjed Seems to me there are two schemes how PHP7 packages are named (at least in Ubuntu what I checked). Either `php-$name` or `php7.0-$name`. I guess we might need a map for that.

**Comment by drybjed** [comment]
I see. Then I suppose that a map in debops.php as a central location, and
separate dependent list of map keys should suffice.
18 wrz 2016 23:23 "Robin Schneider" notifications@github.com napisał(a):

**Comment by nicolas-grekas** [comment]
Same issue here. For the record, here is the list of all existing packages that start with `php7.0-*`. All the others start with `php-*`:
php7.0-cgi
php7.0-cli
php7.0-common
php7.0-curl
php7.0-dev
php7.0-gd
php7.0-gmp
php7.0-json
php7.0-ldap
php7.0-mysql
php7.0-odbc
php7.0-opcache
php7.0-pgsql
php7.0-pspell
php7.0-readline
php7.0-recode
php7.0-snmp
php7.0-sqlite3
php7.0-tidy
php7.0-xml
php7.0-xmlrpc
php7.0-bcmath
php7.0-bz2
php7.0-enchant
php7.0-fpm
php7.0-imap
php7.0-interbase
php7.0-intl
php7.0-mbstring
php7.0-mcrypt
php7.0-phpdbg
php7.0-soap
php7.0-sybase
php7.0-xsl
php7.0-zip
php7.0-dba

**Comment by drybjed** [comment]
I'm looking into a solution to this. For now i have an idea to create a PHP5-PHP7 mapping and add a distribution and release to possible filters, something like this:

```
php__packages:
  - php5: 'php5-apcu'
    php7_0: 'php7.0-apcu'
    distribution: 'Debian'

  - php5: 'php5-apcu'
    php7_0: 'php-apcu'
    distribution: 'Ubuntu'
```

The key will be checked against the current PHP version. It will be extremely verbose, but it should cover the important use cases. Any alternative suggestions?

**Comment by ypid** [comment]
LGTM. Just to clarify, the variable would be called something like `php__packages_map` instead of `php__packages`?

**Comment by drybjed** [comment]
Yes, they will be separate. I was thinking more like:

```
php__alt_packages
php__alt_dependent_packages
```

but I suppose that it could be:

```
php__packages_map
php__dependent_packages_map
```

The '_map` suffix is used through DebOps but in slightly different usage patterns, so I would pick the first version instead. What do you think?

**Comment by ypid** [comment]
The first option sounds good. Maybe even `php__alt_package_names`?

About the `dependent_packages` variable. I think that would be a bad design to add this. `debops.php` should be the one place where such a mapping is maintained. When other roles need packages not yet handled by debops.php then it should be added to debops.php.

**Comment by drybjed** [comment]
@ypid Right, I remember now that we talked about it and it all should be in `debops.php`, good call. I'll try to rewrite the `apt` install task to use a lookup template instead, and handle specific packages depending on rules we set for them.

**Comment by drybjed** [comment]
It looks like the [php-defaults](https://packages.debian.org/source/stretch/php-defaults) source package creates binary `php-*` packages that pull the default versions in Debian/Ubuntu. Not sure when that started, but it seems that the role could switch from installing `php7.0-*` packages directly to installing `php-*` as needed. It looks like all the `php7.0-*` packages and `php7.0` itself are covered by it.

In that case perhaps better solution would be a switch from installing `php<version>` for PHP7+ to `php-*`; at least this would not require a static list of package names. I'll test that to see if it's a viable solution.
