### ISSUE TITLE
php-fpm pool path seems to be broken in Stretch

### ISSUE THREAD

**Issue by evilham** [debops/ansible-php#39]
By default, debops.nginx sets up Nginx to use a pool socket under: `/run/php5,7.0-fpm-{ item.name }.sock`
At least on Stretch however, they are being created under: `/run/php5,7.0/php-fpm-{ item.name }.sock` which results in Nginx replying with a 502 Bad gateway.

Setting the `listen` parameter for the pool manually is a checked workaround.

PS: Haven't tried it on Jessie, I am just assuming this is an issue related to some new config in Stretch and that it used to work before.

**Comment by drybjed** [comment]
Just checked that on a Stretch host and I can confirm the issue. The existing DebOps roles like `debops.dokuwki` most likely will work out of the box, but a switch to a subdirectory on Stretch (and maybe Xenial? not sure) is a good idea.

Thanks for the heads up.

**Comment by evilham** [comment]
I am quite sure this was fixed in the monorepo already, closing.
